apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phishguard-artifacts-pvc
  labels:
    app: phishguard
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
