apiVersion: v1
kind: Service
metadata:
  name: phishguard-service
  labels:
    app: phishguard
spec:
  type: ClusterIP
  selector:
    app: phishguard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
