apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "phishguard.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "phishguard.name" . }}
    helm.sh/chart: {{ include "phishguard.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "phishguard.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "phishguard.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      {{- if .Values.metrics.enabled }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: {{ .Values.metrics.path | quote }}
        prometheus.io/port: {{ .Values.metrics.port | quote }}
      {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            - name: FLASK_ENV
              value: {{ .Values.env.FLASK_ENV | quote }}
            {{- if .Values.env.VIRUSTOTAL_API_KEY }}
            - name: VIRUSTOTAL_API_KEY
              value: {{ .Values.env.VIRUSTOTAL_API_KEY | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /api/soc/threat-level
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /api/soc/threat-level
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: app-artifacts
              mountPath: /app/artifacts
            - name: app-logs
              mountPath: /app/logs
      volumes:
        - name: app-logs
          emptyDir: {}
        - name: app-artifacts
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "phishguard.fullname" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
